DROP TABLE T_GOODS;
CREATE TABLE T_GOODS(
ID NUMBER(6) NOT NULL,
NAME VARCHAR2(20) NOT NULL,
COLOR VARCHAR2(8) NOT NULL,
DISCOUNT VARCHAR2(6),
GOODSNUM NUMBER(8),
GOODSSIZE VARCHAR2(8),
PICTURE VARCHAR2(80),
PRICE VARCHAR2(8),
TYPE VARCHAR2(8),
CONSTRAINT PK_ID PRIMARY KEY(ID)
);
CREATE SEQUENCE SEQ_GOODS
INCREMENT BY 1
START WITH 1
MAXVALUE 999999
MINVALUE 1
NOCYCLE
NOCACHE;

INSERT INTO T_GOODS(ID,NAME,COLOR,DISCOUNT,GOODSNUM,GOODSSIZE,PICTURE,PRICE,TYPE)
 VALUES(SEQ_GOODS.NEXTVAL,'CASIO','RED','0.7',29,'MIDDLE','/images/p-1.png','900','MAN');
 INSERT INTO T_GOODS(ID,NAME,COLOR,DISCOUNT,GOODSNUM,GOODSSIZE,PICTURE,PRICE,TYPE)
 VALUES(SEQ_GOODS.NEXTVAL,'CASIO','gold','0.7',29,'MIDDLE','/images/p-2.png','850','WOMAN');
 INSERT INTO T_GOODS(ID,NAME,COLOR,DISCOUNT,GOODSNUM,GOODSSIZE,PICTURE,PRICE,TYPE)
 VALUES(SEQ_GOODS.NEXTVAL,'Titan','RED','0.7',29,'MIDDLE','/images/p-3.png','740','MAN');
 INSERT INTO T_GOODS(ID,NAME,COLOR,DISCOUNT,GOODSNUM,GOODSSIZE,PICTURE,PRICE,TYPE)
 VALUES(SEQ_GOODS.NEXTVAL,'Sonata','blue','0.7',29,'MIDDLE','/images/p-4.png','300','CHILD');
 INSERT INTO T_GOODS(ID,NAME,COLOR,DISCOUNT,GOODSNUM,GOODSSIZE,PICTURE,PRICE,TYPE)
 VALUES(SEQ_GOODS.NEXTVAL,'Kurtas','yellow','0.7',29,'MIDDLE','/images/p-5.png','1900','MAN');
 INSERT INTO T_GOODS(ID,NAME,COLOR,DISCOUNT,GOODSNUM,GOODSSIZE,PICTURE,PRICE,TYPE)
 VALUES(SEQ_GOODS.NEXTVAL,'Omax','RED','0.7',29,'MIDDLE','/images/p-6.png','320','MAN');
COMMIT;
 